create-inputs
js-tasks-ru/htmlcss-20240614_info-mii pull request #20
Opened 2024-08-01 20:14 UTC by xxxsantaklaysxxx

2024-08-01 20:14 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-08-01 22:02 UTC, GSemikozov requested changes

2024-08-01 22:02 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <div class="form-block form-block__success">
form-block_success

2024-08-01 22:02 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +        <div class="form-block">
form-block_error

2024-08-01 22:02 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <div class="form-block__content form-block__error">
модификатор блока на элементе?

2024-08-04 08:46 UTC, xxxsantaklaysxxx commented on 07-lection5/04-input/index.html
> +        <div class="form-block form-block__success">
исправил

2024-08-04 08:46 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-08-04 08:46 UTC, xxxsantaklaysxxx commented on 07-lection5/04-input/index.html
> +        <div class="form-block">
исправил

2024-08-04 08:47 UTC, xxxsantaklaysxxx commented on 07-lection5/04-input/index.html
> +            <div class="form-block__content form-block__error">
Исправил

2024-08-25 18:44 UTC, GSemikozov approved these changes

2024-08-25 18:44 UTC, merged