03 lection task 2
js-tasks-ru/htmlcss-20240614_info-mii pull request #4
Opened 2024-06-24 05:22 UTC by xxxsantaklaysxxx

2024-06-24 05:22 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-24 13:30 UTC, GSemikozov requested changes

2024-06-24 13:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	display: block;
здесь все стили - лишние)

2024-06-24 13:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	overflow: auto;
лишнее

2024-06-24 13:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
в открытом состоянии у .accordion__text паддинг снизу 32

2024-06-24 13:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .accordion__summary:before {
.accordion__item[open]

2024-06-24 13:30 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .accordion__summary:before {
в целом все эти стили здесь не нужны, если не поворачиваем стрелку

2024-06-26 08:44 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-29 04:46 UTC, GSemikozov requested changes

2024-06-29 04:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	margin-top: 16px;
одновременно и паддинг и марджин? тогда от тайтла до текста будет 32, а в макете - 16

2024-06-29 04:46 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	margin-bottom: 8px;
рекомендую здесь использовать паддинг

2024-07-03 13:41 UTC, GSemikozov submitted a review, later dismissed

2024-07-03 13:41 UTC, jsru-1 commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-07-03 13:42 UTC, GSemikozov approved these changes

2024-07-03 13:42 UTC, merged