04-lection-task-1
js-tasks-ru/htmlcss-20240614_info-mii pull request #5
Opened 2024-06-28 04:57 UTC by xxxsantaklaysxxx

2024-06-28 04:57 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-29 04:47 UTC, GSemikozov requested changes

2024-06-29 04:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_items {
.histogram__items

2024-06-29 04:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_item {
.histogram__item

2024-06-29 04:47 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-wrap: wrap;
nowrap

2024-06-30 17:40 UTC, xxxsantaklaysxxx commented on 04-lection2/01-histogram/histogram.css
> +.histogram_items {
Исправил

2024-06-30 17:40 UTC, xxxsantaklaysxxx commented on 04-lection2/01-histogram/histogram.css
> +    flex-wrap: wrap;
Исправил

2024-06-30 17:40 UTC, xxxsantaklaysxxx commented on 04-lection2/01-histogram/histogram.css
> +.histogram_item {
Исправил

2024-07-03 13:41 UTC, GSemikozov approved these changes

2024-07-03 13:41 UTC, merged